version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github_action:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      java:
        patterns:
          - "*"
