name: keycloak-cloudfront-auth

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KCA_KC_VERSION}
    container_name: kc-cloudfront-auth_keycloak
    environment:
      - KEYCLOAK_ADMIN=${KCA_KC_ADMIN_USER}                   # KC <= 25.0
      - KEYCLOAK_ADMIN_PASSWORD=${KCA_KC_ADMIN_PASSWORD}      # KC <= 25.0
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KCA_KC_ADMIN_PASSWORD}  # KC >= 26.0
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KCA_KC_ADMIN_USER}      # KC >= 26.0
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_PORT=80
      - KC_LOG_LEVEL=${KCA_KC_LOG_LEVEL}
      - KC_PROXY_HEADERS=xforwarded
      - KC_SPI_REALM_RESTAPI_EXTENSION_CLOUDFRONT_AUTH_REDIRECT_DELAY=${KCA_KC_AUTH_REDIRECT_DELAY}
      - KC_SPI_REALM_RESTAPI_EXTENSION_CLOUDFRONT_AUTH_REDIRECT_FALLBACK_DELAY=${KCA_KC_AUTH_REDIRECT_FALLBACK_DELAY}
    ports:
      - "${KCA_KC_HOST_PORT}:80"
    command:
      - start-dev
    volumes:
      - ./mounts/kc_providers:/opt/keycloak/providers:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 2s
      retries: 15

  configurator:
    image: eclipse-temurin:21
    container_name: kc-cloudfront-auth_configurator
    environment:
      - KEYCLOAK_VERSION=${KCA_KC_VERSION}
      - KCA_KC_ADMIN_PASSWORD=${KCA_KC_ADMIN_PASSWORD}
      - KCA_KC_ADMIN_USER=${KCA_KC_ADMIN_USER}
      - KCA_KC_CLIENT_ID=${KCA_KC_CLIENT_ID}
      - KCA_KC_CLIENT_SECRET=${KCA_KC_CLIENT_SECRET}
      - KCA_KC_REALM_NAME=${KCA_KC_REALM_NAME}
      - KCA_OPENRESTY_HOST_PORT=${KCA_OPENRESTY_HOST_PORT}
    volumes:
      - ./mounts/configurator:/mnt/docker:ro
    command: sh /mnt/docker/configure.sh

  cf-auth-sim:
    image: openresty/openresty:alpine-fat
    container_name: kc-cloudfront-auth_cf-auth-sim
    environment:
      - DEBUG_PAGE_NO_AUTH=${KCA_DEBUG_PAGE_NO_AUTH}
      - KC_REALM_NAME=${KCA_KC_REALM_NAME}
      - KC_CLIENT_ID=${KCA_KC_CLIENT_ID}
      - KC_CLIENT_SECRET=${KCA_KC_CLIENT_SECRET}
      - KC_CF_SIGN_KEY_ID=${KCA_CF_SIGN_KEY_ID}
      - KC_URL=http://localhost:${KCA_KC_HOST_PORT}
      - KC_INTERNAL_URL=http://kc-cloudfront-auth_keycloak
      - APP_URL=
    ports:
      - "${KCA_OPENRESTY_HOST_PORT}:80"
    volumes:
      - ./mounts/cf-auth-sim:/mnt/docker:ro
      - ./mounts/cf-auth-sim/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    command: >
      sh -c "
        luarocks install lua-resty-rsa &&
        luarocks install lua-resty-template &&
        luarocks install lua-resty-http &&
        luarocks install lua-resty-openssl &&
        /usr/local/openresty/bin/openresty -g 'daemon off;'
      "
